# tack pins

[shorturls]
channel = "https://channels.nixos.org/{path}/nixexprs.tar.zst"
gh = "github:{path}"

[all_follow]
nixpkgs = "nixpkgs"

[inputs.darwin]
url = "gh:nix-darwin/nix-darwin"

[inputs.den]
exclude_follow = ["nixpkgs"]
url = "gh:denful/den"

[inputs.flake-parts]
exclude_follow = ["nixpkgs"]
url = "gh:hercules-ci/flake-parts"

[inputs.home-manager]
url = "gh:nix-community/home-manager/master"

[inputs.import-tree]
url = "gh:denful/import-tree"

[inputs.nixos-apple-silicon]
url = "gh:nix-community/nixos-apple-silicon"

[inputs.nixpkgs]
url = "channel:nixpkgs-unstable"
# url = "gh:nixos/nixpkgs/nixpkgs-unstable"

[inputs.noctalia]
url = "gh:noctalia-dev/noctalia"

[inputs.noctalia-greeter]
url = "gh:noctalia-dev/noctalia-greeter"

[inputs.shellpers]
url = "gh:quinneden/shellpers"

[inputs.virby]
url = "gh:quinneden/virby-nix-darwin"

[inputs.zen-browser]
follows = { home-manager = "home-manager" }
url = "gh:0xc000022070/zen-browser-flake"

[inputs.tack]
url = "gh:manic-systems/tack"

[inputs.steam-asahi]
url = "gh:sm-idk/steam-asahi/feature/arm64-client"

[inputs.alternative-linux-builder]
url = "gh:quinneden/alternative-linux-builder"
