{
  homebrew = {
    enable = true;
    global.brewfile = true;

    onActivation = {
      autoUpdate = true;
      cleanup = "zap";
      extraFlags = [ "--quiet" ];
    };

    taps = [
      "homebrew/bundle"
      "homebrew/services"
      "iina/homebrew-mpv-iina"
      "slp/krunkit"
      "sst/tap"
    ];

    casks = [
      "betterdisplay"
      "container"
      "element"
      "iina"
      "iterm2"
      "macfuse"
      "notion"
      "obsidian"
      "pearcleaner"
      "podman-desktop"
      "tailscale-app"
      "utm"
      "zen"
      "zed@preview"
    ];

    brews = [
      "aria2"
      "awscli"
      "bat"
      "bazelisk"
      "bzip2"
      "chroma"
      "cmake"
      "commitizen"
      "coreutils"
      "curl"
      "eza"
      "fd"
      "ffmpeg"
      "fileicon"
      "gcc"
      "gh"
      "git"
      "git-lfs"
      "github-mcp-server"
      "glow"
      "gnu-sed"
      "gnupg"
      "go"
      "gobject-introspection"
      "gptfdisk"
      "gum"
      "hugo"
      "jq"
      "just"
      "ldid"
      "lftp"
      "libb2"
      "libepoxy"
      "libffi"
      "lima"
      "llvm"
      "lzip"
      "lzo"
      "make"
      "marksman"
      "mas"
      "meson"
      "most"
      "ncdu"
      "node"
      "openssl@3"
      "perl"
      "pipenv"
      "pipx"
      "pkg-config"
      "podman"
      "podman-compose"
      "pv"
      "qemu"
      "rbenv"
      "rclone"
      "ripgrep"
      "rsync"
      "rustup"
      "shellcheck"
      "slp/krunkit/krunkit"
      "slp/krunkit/libkrun-efi"
      "slp/krunkit/molten-vk-krunkit"
      "slp/krunkit/virglrenderer"
      "socat"
      "sst/tap/opencode"
      "superhtml"
      "tlrc"
      "tree"
      "uv"
      "watch"
      "wget"
      "yq"
      "zbar"
      "zlib"
    ];
  };
}
