{
  homebrew = {
    brews = [
      "aria2"
      "ast-grep"
      "awscli"
      "bottom"
      "buildifier"
      "fx"
      "gemini-cli"
      "git"
      "glab"
      "go"
      "gum"
      "k9s"
      "mise"
      "nushell"
      "openssh"
      "python-lsp-server"
      "ruff"
      "rustup"
      "shellcheck"
      "shfmt"
      "superhtml"
      "tldr"
      "tmux"
      "tree"
      "wget"
      "xcodes"
    ];
    casks = [
      "betterdisplay"
      "font-victor-mono-nerd-font"
      "ghostty@tip"
      "obsidian"
      "podman-desktop"
      "tailscale-app"
      "utm@beta"
      "zed"
    ];
  };
}
